#!/bin/bash

go test -count=1 ./...

if [ $? -ne 0 ]; then
  echo "Commit rejected: Please fix tests before commit"
  exit 1
fi

golangci-lint run --new-from-rev=HEAD~1 > /dev/null 2>&1
if [ $? -ne 0 ]; then
  echo "Commit rejected: Please run 'golangci-lint run --new-from-rev=HEAD~1' and fix the problems"
  exit 1
fi
